<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMW9zT4k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMW9zT4k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMW9zT4k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMW9zT4k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMW9zT4k\App_KernelDevDebugContainer([
    'container.build_hash' => 'MW9zT4k',
    'container.build_id' => '2f906565',
    'container.build_time' => 1711721980,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMW9zT4k');
