<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfWNyjy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfWNyjy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfWNyjy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfWNyjy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXfWNyjy\App_KernelDevDebugContainer([
    'container.build_hash' => 'XfWNyjy',
    'container.build_id' => 'b822bf1d',
    'container.build_time' => 1711621359,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfWNyjy');
