<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiG3mCH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiG3mCH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXiG3mCH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXiG3mCH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXiG3mCH\App_KernelDevDebugContainer([
    'container.build_hash' => 'XiG3mCH',
    'container.build_id' => '1dbf5a8f',
    'container.build_time' => 1711724235,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiG3mCH');
